### ISSUE TITLE
Bug: Game Summary Displays Incorrect Data

### ISSUE THREAD

**Issue by Powan55** [Powan55/Trivial-Trivia#23]
Currently, the game summary feature in our application is displaying incorrect or placeholder data, showing "Game Summary" without providing relevant user performance statistics. This is a critical issue as it misleads users and fails to deliver the intended functionality of providing feedback on their performance. The game summary should accurately reflect the user's performance, including the number of questions answered correctly and incorrectly, along with the final score when the user chooses to exit the game.

**Comment by Powan55** [comment]
@Uttamb7  Can you please investigate this issue? 

To recreate the issue of the game summary displaying incorrect data, follow these steps:

1. Start a New Game Session as Logged-in User:
2. Answer Questions Correctly and Incorrectly:
3. Choose to Exit the Game once the Game is over
4. Observe the Displayed Game Summary

**Comment by Uttamb7** [comment]
@Powan55 
When looking into the issue it seems that we didn't have any variable or functions to keep track of right and wrong answers, therefore it wasn't displaying properly. 

- Created getter's and setters for User interface
- Updated the proxy user to correctly implement the getters and setters
- Updated Real users to correctly Implement the getters and setters 
- Added a little additional feature to enhance user experience by stating if the user got the question correct or incorrect within that question.

The game now displays "Correct" if the user got the question right and "Incorrect ;(" for the wrong answers. After exiting the game you can go to "View Stat" and see the new stat updated like score, right answers, wrong answers.

**Comment by Powan55** [comment]
Please implement this and create the pull request
