### ISSUE TITLE
Make a new Login Page

### ISSUE THREAD

**Issue by Uttamb7** [Powan55/Trivial-Trivia#39]
We need to design and implement a new login page for the Trivial Trivia application to enhance user experience and provide a more intuitive interface. The current login lacks the visual appeal and functionality that users expect, and it does not effectively showcase the features of our game.

**Comment by Powan55** [comment]
Closing this issue as the task to create a new login page has been successfully completed under issue #36. Any further changes or enhancements required for the login page should be addressed in a new issue.
